import React, { useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowLeft, Check, ChevronLeft, Coffee, Heart, HelpCircle, MapPin, Menu, Minus, Plus, Search, ShoppingBag, Star, Trash2, X } from 'lucide-react'
import './styles.css'

const drinks = [
  { id: 1, name: 'إسبريسو بُنّة', en: 'BUNNA ESPRESSO', desc: 'شوت مركز بطعم شوكولاتة وبندق محمّص', price: 65, tag: 'الأكثر طلبًا', emoji: '☕', color: 'dark', category: 'hot' },
  { id: 2, name: 'سبانيش لاتيه', en: 'SPANISH LATTE', desc: 'إسبريسو، لبن كريمي وحليب مكثف على مزاجك', price: 115, tag: 'ترند', emoji: '🥛', color: 'cream', category: 'sweet' },
  { id: 3, name: 'آيسد فرابيه', en: 'ICED FRAPPÉ', desc: 'قهوة مثلجة مخفوقة وكريمة فانيليا خفيفة', price: 135, tag: 'بارد', emoji: '🧋', color: 'cold', category: 'cold' },
  { id: 4, name: 'فلات وايت', en: 'FLAT WHITE', desc: 'دبل إسبريسو وفوم لبن ناعم ومظبوط', price: 95, emoji: '☕', color: 'latte', category: 'hot' },
]

const menuFilters = [
  { id: 'all', label: 'الكل' },
  { id: 'hot', label: 'ساخن' },
  { id: 'cold', label: 'بارد' },
  { id: 'sweet', label: 'حلويات' },
]

function App() {
  const [page, setPage] = useState('home')
  const [cart, setCart] = useState([])
  const [drawer, setDrawer] = useState(false)
  const [toast, setToast] = useState('')
  const total = useMemo(() => cart.reduce((s, x) => s + x.price * x.qty, 0), [cart])
  const add = (item) => { setCart(c => { const found = c.find(x => x.id === item.id); return found ? c.map(x => x.id === item.id ? {...x, qty:x.qty+1} : x) : [...c, {...item, qty:1}] }); setToast('أُضيفت القهوة إلى سلتك'); setTimeout(()=>setToast(''),1800) }
  const change = (id, d) => setCart(c => c.flatMap(x => x.id === id ? (x.qty + d > 0 ? [{...x,qty:x.qty+d}] : []) : [x]))
  const nav = (p) => { setPage(p); setDrawer(false); window.scrollTo({top:0, behavior:'smooth'}) }
  return <div dir="rtl" className="min-h-screen bg-[#f6f1e8] text-[#21140f]">
    <header className="sticky top-0 z-30 border-b border-[#3c251a]/10 bg-[#f6f1e8]/90 backdrop-blur">
      <div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8">
        <button onClick={()=>setDrawer(true)} className="grid size-10 place-items-center rounded-full border border-[#3c251a]/15 lg:hidden"><Menu size={20}/></button>
        <button onClick={()=>nav('home')} className="flex items-center gap-2"><span className="grid size-10 place-items-center rounded-full bg-[#2b1710] text-[#f3c96b]"><Coffee size={20}/></span><span className="brand text-2xl">بُنّة</span></button>
        <nav className="hidden items-center gap-8 text-sm font-semibold lg:flex"><button className={page==='home'?'active-nav':''} onClick={()=>nav('home')}>الرئيسية</button><button onClick={()=>nav('story')}>قصتنا</button><button onClick={()=>document.getElementById('menu').scrollIntoView({behavior:'smooth'})}>المنيو</button><button onClick={()=>nav('help')}>المساعدة</button></nav>
        <button onClick={()=>setDrawer(true)} className="relative grid size-11 place-items-center rounded-full bg-[#2b1710] text-white"><ShoppingBag size={19}/>{cart.length>0&&<span className="absolute -left-1 -top-1 grid size-5 place-items-center rounded-full bg-[#d69035] text-[10px] font-bold text-[#2b1710]">{cart.reduce((s,x)=>s+x.qty,0)}</span>}</button>
      </div>
    </header>
    {page==='home' && <Home add={add} nav={nav}/>} {page==='story' && <Story nav={nav}/>} {page==='help' && <Help nav={nav}/>} 
    <footer className="bg-[#25150f] px-6 py-12 text-[#eadccc]"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 md:flex-row"><div><div className="brand text-3xl text-[#f2c766]">بُنّة</div><p className="mt-3 max-w-xs text-sm leading-7 text-[#c5b2a1]">قهوة مظبوطة لليوم اللي محتاج يصحصح.</p></div><div className="flex gap-12 text-sm"><div><p className="mb-3 text-[#f2c766]">زورنا</p><p className="text-[#c5b2a1]">كل يوم، ٧ ص — ١١ م</p></div><div><p className="mb-3 text-[#f2c766]">تواصل</p><p className="text-[#c5b2a1]">hello@bunna.coffee</p></div></div></div></footer>
    {drawer && <Cart drawerClose={()=>setDrawer(false)} cart={cart} change={change} total={total} nav={nav}/>} {toast && <div className="fixed bottom-6 left-1/2 z-50 -translate-x-1/2 rounded-full bg-[#25150f] px-5 py-3 text-sm text-white shadow-xl">{toast}</div>}
  </div>
}

function Home({add,nav}) {
  const [selectedFilter, setSelectedFilter] = useState('all')
  const [menuQuery, setMenuQuery] = useState('')
  const visibleDrinks = drinks.filter(item => {
    const matchesCategory = selectedFilter === 'all' ? true : item.category === selectedFilter
    const haystack = `${item.name} ${item.en} ${item.desc}`.toLowerCase()
    const matchesQuery = haystack.includes(menuQuery.trim().toLowerCase())
    return matchesCategory && matchesQuery
  })

  return <>
  <section className="hero mx-auto mt-5 max-w-[1440px] overflow-hidden rounded-[2rem] px-7 py-12 lg:px-20 lg:py-24"><div className="relative z-10 max-w-xl"><div className="mb-6 flex w-fit items-center gap-2 rounded-full border border-[#f5d88f]/35 bg-[#2b1710]/45 px-4 py-2 text-xs text-[#f5d88f]"><span className="size-1.5 rounded-full bg-[#f2c766]"/> قهوتك المظبوطة، في أي وقت</div><h1 className="brand text-5xl leading-[1.15] text-[#fff7e9] md:text-7xl">اصحى على<br/><em className="not-italic text-[#e9b957]">مزاجك.</em></h1><p className="mt-7 max-w-md text-base leading-8 text-[#e7d6c4]">من أول شوت إسبريسو لحد آخر رشفة فرابيه. قهوة متحضرة بحب عشان يومك يبقى أحلى.</p><div className="mt-9 flex flex-wrap gap-3"><button onClick={()=>document.getElementById('menu').scrollIntoView({behavior:'smooth'})} className="rounded-full bg-[#f0c766] px-6 py-3.5 text-sm font-bold text-[#2b1710] transition hover:bg-[#fff0b7]">اطلب دلوقتي <ArrowLeft className="mr-2 inline" size={16}/></button><button onClick={()=>nav('story')} className="rounded-full border border-white/35 px-6 py-3.5 text-sm font-bold text-white transition hover:bg-white/10">حكاية بُنّة</button></div></div><CoffeeMachine/><div className="absolute bottom-8 left-8 text-[10px] tracking-[.28em] text-[#e5c16c]">BUNNA · COFFEE & GOOD MOOD</div></section>
  <section className="mx-auto grid max-w-7xl grid-cols-1 gap-4 px-5 py-10 md:grid-cols-3 lg:px-8"><Stat n="١٠٠٪" t="حبوب مختارة بعناية"/><Stat n="١٢" t="ساعة من التحميص للتقديم"/><Stat n="٤.٩" t="تقييم عشاق بُنّة"/></section>
  <section id="menu" className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow">منيو اليوم</p><h2 className="brand mt-2 text-4xl md:text-5xl">اختَر مزاجك.</h2></div><div className="flex gap-2 overflow-auto">{menuFilters.map(filter => <button key={filter.id} type="button" onClick={()=>setSelectedFilter(filter.id)} className={'pill ' + (selectedFilter === filter.id ? 'selected' : '')}>{filter.label}</button>)}</div></div><div className="mt-6 relative"><Search className="absolute right-4 top-3.5 text-[#80695b]" size={18}/><input value={menuQuery} onChange={(e)=>setMenuQuery(e.target.value)} className="w-full rounded-full border border-[#3c251a]/10 bg-white py-3 pr-11 pl-5 outline-none focus:border-[#a8612e]" placeholder="ابحث عن القهوة أو النكهة..." /></div>{visibleDrinks.length > 0 ? <div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{visibleDrinks.map(x=><Drink key={x.id} item={x} add={add}/>)}</div> : <div className="mt-10 rounded-3xl border border-dashed border-[#3c251a]/20 bg-[#fbf8f2] p-10 text-center"><p className="brand text-3xl text-[#2b1710]">ما لقينا قهوة مناسبة</p><p className="mt-3 text-sm text-[#725c4d]">جرب كلمة ثانية أو غيّر فلتر المنيو.</p><button type="button" onClick={()=>{setMenuQuery(''); setSelectedFilter('all')}} className="mt-5 rounded-full bg-[#2b1710] px-5 py-3 text-sm font-bold text-white">إظهار الكل</button></div>}</section>
  <section className="mx-auto mb-20 grid max-w-7xl overflow-hidden rounded-[2rem] bg-[#d9c0a0] lg:grid-cols-2"><div className="p-9 md:p-14"><p className="eyebrow text-[#80542e]">روتين بُنّة اليومي</p><h2 className="brand mt-3 text-4xl leading-tight md:text-5xl">دقيقة ليك،<br/>فرق كبير.</h2><p className="mt-5 max-w-md leading-8 text-[#5e402c]">القهوة مش بس مشروب؛ دي البريك الصغير وسط الزحمة، واللمة الحلوة في أول اليوم.</p><button onClick={()=>nav('story')} className="mt-8 text-sm font-bold underline underline-offset-8">إحنا بدأنا إزاي؟</button></div><div className="story-pattern min-h-64"/></section>
  </> }
const Stat=({n,t})=><div className="rounded-2xl border border-[#3c251a]/10 bg-[#fbf8f2] p-6"><div className="brand text-3xl text-[#9a5928]">{n}</div><p className="mt-2 text-sm text-[#6a5141]">{t}</p></div>
function CoffeeMachine(){
  const [status,setStatus]=useState('idle')
  const brew=()=>{ if(status==='brewing') return; setStatus('brewing'); setTimeout(()=>setStatus('done'),3600) }
  return <div className="hero-machine machine-stage" onMouseEnter={brew} onFocus={brew} tabIndex="0" aria-label="مرر المؤشر لبدء تحضير الإسبريسو"><div className={'espresso-machine '+status}><div className="steam"><i/><i/><i/></div><div className="machine-top"><div className="machine-brand">BUNNA</div><div className="machine-lights"><i/><i/><i/></div></div><div className="machine-face"><div className="machine-gauge"><span>BAR</span><b>9</b></div><div className="machine-buttons"><i/><i/></div><div className="machine-group"><div className="portafilter"/><div className="spouts"><i/><i/></div></div><div className="espresso-stream"/></div><div className="machine-base"/><div className="cup"><div className="crema"/><span>بُنّة</span></div></div><p className="machine-caption">{status==='idle'?'قرّب الماوس وحضّر فنجانك':status==='brewing'?'الإسبريسو بيتحضّر…':'إسبريسو بُنّة · ٣٦ جرام'}</p></div>
}
function Drink({item,add}) { return <article className="group rounded-3xl bg-[#fbf8f2] p-4 shadow-sm transition hover:-translate-y-1 hover:shadow-xl hover:shadow-[#5d3420]/10"><div className={'drink-art '+item.color}><span>{item.emoji}</span>{item.tag&&<b>{item.tag}</b>}</div><div className="px-1 pt-5"><p className="text-[10px] uppercase tracking-[.16em] text-[#9d7a63]">{item.en}</p><h3 className="brand mt-1 text-2xl">{item.name}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-[#725c4d]">{item.desc}</p><div className="mt-5 flex items-center justify-between"><b className="text-[#9a5928]">{item.price} ج.م</b><button onClick={()=>add(item)} className="grid size-10 place-items-center rounded-full bg-[#2b1710] text-white transition group-hover:bg-[#a8612e]"><Plus size={18}/></button></div></div></article> }
function Story({nav}) { return <main className="mx-auto max-w-5xl px-5 py-16 lg:py-24"><p className="eyebrow">حكاية بُنّة</p><h1 className="brand mt-3 text-5xl leading-tight md:text-7xl">بدأنا بسؤال بسيط:<br/><span className="text-[#a8612e]">إزاي اليوم يبقى ألذ؟</span></h1><div className="mt-14 grid gap-10 md:grid-cols-[1fr_.9fr]"><div className="space-y-6 text-lg leading-9 text-[#644737]"><p>في بُنّة، بنحب القهوة اللي بتفوقك من غير تعقيد. بنهتم بحرارة الفنجان، ريحة البن، وأول رشفة بتظبط لك اليوم.</p><p>اسمنا بسيط وقريب: بُنّة. لأن الحكاية كلها بتبدأ من حباية بن، وتتكمّل مع أصحابك ومشاويرك.</p><button onClick={()=>nav('home')} className="rounded-full bg-[#2b1710] px-6 py-3 text-sm font-bold text-white">يلا نضبطها</button></div><div className="rounded-[2rem] bg-[#2b1710] p-8 text-[#f7e7cc]"><Coffee className="text-[#e3b858]" size={32}/><p className="brand mt-16 text-3xl leading-relaxed">“كل فنجان حكاية، خلّي حكايتك بُنّة.”</p><div className="mt-10 border-t border-white/15 pt-5 text-sm text-[#cbb7a3]">اتأسست بُنّة في ٢٠٢٤ · القاهرة</div></div></div></main> }
function Help(){ const qs=['كيف أتتبع طلبي؟','هل يمكنني تعديل طلبي؟','ما هي طرق الدفع المتاحة؟','كيف أتواصل مع فريق نَثْر؟']; return <main className="mx-auto max-w-3xl px-5 py-16 lg:py-24"><div className="text-center"><div className="mx-auto grid size-14 place-items-center rounded-full bg-[#ead6b8] text-[#80542e]"><HelpCircle/></div><p className="eyebrow mt-5">نحن هنا لأجلك</p><h1 className="brand mt-2 text-5xl">كيف نساعدك؟</h1><div className="relative mt-8"><Search className="absolute right-4 top-3.5 text-[#80695b]" size={18}/><input className="w-full rounded-full border border-[#3c251a]/10 bg-white py-3 pr-11 pl-5 outline-none focus:border-[#a8612e]" placeholder="ابحث في الأسئلة الشائعة..."/></div></div><div className="mt-10 space-y-3">{qs.map(q=><button key={q} className="flex w-full items-center justify-between rounded-2xl bg-white p-5 text-right font-semibold shadow-sm"><ChevronLeft size={18}/>{q}</button>)}</div><div className="mt-10 rounded-3xl bg-[#e7d3b4] p-7 text-center"><p className="brand text-2xl">لم تجد ما تبحث عنه؟</p><p className="mt-2 text-sm text-[#684a38]">فريقنا يرد عليك يوميًا من ٧ صباحًا حتى ١١ مساءً.</p><button className="mt-5 rounded-full bg-[#2b1710] px-5 py-3 text-sm font-bold text-white">راسلنا عبر واتساب</button></div></main> }
function Cart({drawerClose,cart,change,total,nav}) { const [ordered,setOrdered]=useState(false); return <div className="fixed inset-0 z-40 bg-black/35" onClick={drawerClose}><aside className="mr-auto flex h-full w-full max-w-md flex-col bg-[#fbf8f2] p-6 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><button onClick={drawerClose} className="grid size-10 place-items-center rounded-full bg-[#eee5d8]"><X size={19}/></button><h2 className="brand text-3xl">سلتك</h2></div>{ordered?<div className="my-auto text-center"><div className="mx-auto grid size-16 place-items-center rounded-full bg-[#dce8d6] text-[#48723e]"><Check/></div><h3 className="brand mt-5 text-3xl">طلبك اتسجل</h3><p className="mt-2 text-sm text-[#725c4d]">فنجانك هيكون جاهز خلال ١٢ دقيقة.</p><button onClick={()=>{drawerClose();nav('home')}} className="mt-8 rounded-full bg-[#2b1710] px-6 py-3 text-sm text-white">ارجع للرئيسية</button></div>:cart.length===0?<div className="my-auto text-center text-[#80695b]"><ShoppingBag className="mx-auto mb-4" size={36}/><p className="brand text-2xl">السلة مستنية مزاجك</p><button onClick={drawerClose} className="mt-5 text-sm font-bold underline">شوف المنيو</button></div>:<><div className="mt-8 flex-1 space-y-5 overflow-auto">{cart.map(x=><div key={x.id} className="flex gap-3 border-b border-[#3c251a]/10 pb-5"><div className={'grid size-14 place-items-center rounded-2xl drink-art '+x.color}><span className="text-2xl">{x.emoji}</span></div><div className="flex-1"><p className="font-bold">{x.name}</p><p className="mt-1 text-sm text-[#9a5928]">{x.price} ج.م</p><div className="mt-2 flex items-center gap-3"><button onClick={()=>change(x.id,1)}><Plus size={15}/></button><span className="text-sm">{x.qty}</span><button onClick={()=>change(x.id,-1)}><Minus size={15}/></button></div></div></div>)}</div><div className="border-t border-[#3c251a]/10 pt-5"><div className="mb-4 flex justify-between font-bold"><span>{total} ج.م</span><span>الإجمالي</span></div><button onClick={()=>setOrdered(true)} className="w-full rounded-full bg-[#2b1710] py-4 text-sm font-bold text-white">أكّد الطلب <ArrowLeft className="mr-2 inline" size={16}/></button></div></>}</aside></div> }
createRoot(document.getElementById('root')).render(<App />)
